build: off
environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '6'
    - nodejs_version: '4'
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm prune
test_script:
  - npm test
